server:
  servlet:
    encoding:
      force: true
  error:
    include-stacktrace: never

spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoint:
    health:
      show-details: always